export const ERROR_CODE = {
  SUCCESS: 200,
  FAIL: 500,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,

  USER_NOT_FOUND: 1001,
  USER_PASSWORD_ERROR: 1002,
  USER_ALREADY_EXIST: 1003,
  USER_DISABLED: 1004,

  TOKEN_INVALID: 2001,
  TOKEN_EXPIRED: 2002,
  TOKEN_EMPTY: 2003,

  EXAM_NOT_FOUND: 3001,
  EXAM_NOT_STARTED: 3002,
  EXAM_ENDED: 3003,
  EXAM_ALREADY_TAKEN: 3004,

  PAPER_NOT_FOUND: 4001,
  PAPER_NO_QUESTIONS: 4002,

  QUESTION_NOT_FOUND: 5001,

  SUBJECT_NOT_FOUND: 6001,

  PARAM_ERROR: 7001,
  PARAM_EMPTY: 7002,

  FILE_UPLOAD_ERROR: 8001,
  FILE_TYPE_ERROR: 8002,
  FILE_SIZE_ERROR: 8003,

  DATABASE_ERROR: 9001,
  SYSTEM_ERROR: 9999
}

export const ERROR_MESSAGE = {
  [ERROR_CODE.SUCCESS]: '操作成功',
  [ERROR_CODE.FAIL]: '操作失败',
  [ERROR_CODE.BAD_REQUEST]: '请求参数错误',
  [ERROR_CODE.UNAUTHORIZED]: '未授权，请先登录',
  [ERROR_CODE.FORBIDDEN]: '无权限访问',
  [ERROR_CODE.NOT_FOUND]: '资源不存在',

  [ERROR_CODE.USER_NOT_FOUND]: '用户不存在',
  [ERROR_CODE.USER_PASSWORD_ERROR]: '用户名或密码错误',
  [ERROR_CODE.USER_ALREADY_EXIST]: '用户已存在',
  [ERROR_CODE.USER_DISABLED]: '用户已被禁用',

  [ERROR_CODE.TOKEN_INVALID]: 'Token无效',
  [ERROR_CODE.TOKEN_EXPIRED]: 'Token已过期',
  [ERROR_CODE.TOKEN_EMPTY]: 'Token不能为空',

  [ERROR_CODE.EXAM_NOT_FOUND]: '考试不存在',
  [ERROR_CODE.EXAM_NOT_STARTED]: '考试未开始',
  [ERROR_CODE.EXAM_ENDED]: '考试已结束',
  [ERROR_CODE.EXAM_ALREADY_TAKEN]: '您已参加过此次考试',

  [ERROR_CODE.PAPER_NOT_FOUND]: '试卷不存在',
  [ERROR_CODE.PAPER_NO_QUESTIONS]: '试卷没有题目',

  [ERROR_CODE.QUESTION_NOT_FOUND]: '题目不存在',

  [ERROR_CODE.SUBJECT_NOT_FOUND]: '学科不存在',

  [ERROR_CODE.PARAM_ERROR]: '参数错误',
  [ERROR_CODE.PARAM_EMPTY]: '参数不能为空',

  [ERROR_CODE.FILE_UPLOAD_ERROR]: '文件上传失败',
  [ERROR_CODE.FILE_TYPE_ERROR]: '文件类型不支持',
  [ERROR_CODE.FILE_SIZE_ERROR]: '文件大小超出限制',

  [ERROR_CODE.DATABASE_ERROR]: '数据库操作错误',
  [ERROR_CODE.SYSTEM_ERROR]: '系统异常'
}

export function getErrorMessage(code) {
  return ERROR_MESSAGE[code] || '未知错误'
}
